---
- name: Install WordPress on Amazon Linux 2
  hosts: web
  become: yes
  tasks:
    - name: Update all packages
      yum:
        name: "*"
        state: latest

    - name: Install PHP
      yum:
        name: php
        state: present

    - name: Install PHP MySQLi extension
      yum:
        name: php-mysqli
        state: present

    - name: Start and enable Apache
      service:
        name: httpd
        state: started
        enabled: yes

    - name: Install MariaDB 10.5
      yum:
        name: mariadb105
        state: present

    - name: Start and enable PHP-FPM
      service:
        name: php-fpm
        state: started
        enabled: yes

    - name: Add ec2-user to apache group
      user:
        name: ec2-user
        groups: apache
        append: yes

    - name: Change ownership of /var/www/html to ec2-user:apache
      file:
        path: /var/www/html
        owner: ec2-user
        group: apache
        recurse: yes

    - name: Change ownership of /var/www/html to apache:apache
      file:
        path: /var/www/html
        owner: apache
        group: apache
        recurse: yes

    - name: Download WordPress
      get_url:
        url: https://wordpress.org/latest.zip
        dest: /tmp/latest.zip

    - name: Unzip WordPress
      unarchive:
        src: /tmp/latest.zip
        dest: /tmp
        remote_src: yes
        creates: /tmp/wordpress

    - name: Copy WordPress files to /var/www/html
      command: cp -R /tmp/wordpress/. /var/www/html/
      args:
        removes: /tmp/wordpress

    - name: Set permissions for WordPress files
      file:
        path: /var/www/html
        owner: apache
        group: apache
        mode: '0755'
        recurse: yes

    - name: Restart Apache
      service:
        name: httpd
        state: restarted
   
