---
- name: Install Apache on Amazon Linux
  hosts: web
  become: yes
  tasks:
    - name: Update yum cache
      yum:
        name: '*'
        state: latest

    - name: Install Apache
      yum:
        name: httpd
        state: present

    - name: Ensure Apache is running
      service:
        name: httpd
        state: started
        enabled: yes
